### ISSUE TITLE
Gulp.start is deprecated, yet is still used in watch.js

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#338]
`gulp.start` has been deprecated in gulp v4 but is used in [watch.js](https://github.com/usebedrock/bedrock/blob/master/core/tasks/watch.js), this leads to errors of this type:

```
(node:7976) UnhandledPromiseRejectionWarning: TypeError: gulp.start is not a function
    at /Users/johanronsse/Sites/my-bs5-prototype/core/tasks/watch.js:9:67
    at write (/Users/johanronsse/Sites/my-bs5-prototype/node_modules/gulp-watch/index.js:148:3)
    at /Users/johanronsse/Sites/my-bs5-prototype/node_modules/gulp-watch/index.js:131:5
```

Steps to reproduce:

Start a Bedrock project and add Bootstrap

    npm i bootstrap@5.0.0-alpha2

In the SCSS file

    // Bootstrap
    @import "./node_modules/bootstrap/scss/bootstrap"

Now the error should appear.

**Comment by Wolfr** [comment]
It looks like we will need to rewrite this watch flow using gulp 4 logic.

**Comment by Wolfr** [comment]
The watch.js file does the following:

* Watch SCSS files to compile Sass
* Watch assets folder to copy over images, favicon, fonts and resources,
* Compile icon font when icon font source files change
* Trigger browsersync when icon source files change
* Bundle JS when javascript files change

Code-wise I figured it out I think.

**Comment by Wolfr** [comment]
https://github.com/usebedrock/bedrock
